sudo: required
language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"
  - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/web.git ${HOME}/web -b 7.0
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc

script:
  - travis_run_tests

after_success:
  coveralls
